# Generated by Django 6.0.5 on 2026-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerorder',
            name='vehicle',
            field=models.CharField(choices=[('Motorbike express delivery', 'Motorbike express delivery'), ('Small cargo van', 'Small cargo van'), ('Medium truck', 'Medium truck'), ('Large flatbed truck', 'Large flatbed truck'), ('Refrigerated truck', 'Refrigerated truck')], max_length=80),
        ),
    ]
