# Generated by Django 6.0.5 on 2026-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_consumerorder_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce/'),
        ),
    ]
