# Generated by Django 6.0.3 on 2026-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_farmerlisting_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='FarmerListing',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ConsumerOrder',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
